docker pull ccr.ccs.tencentyun.com/cube-studio/deploy-service:20240601 && docker save ccr.ccs.tencentyun.com/cube-studio/deploy-service:20240601 | gzip > ccr.ccs.tencentyun.com-cube-studio-deploy-service-20240601.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu22.04 && docker save ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu22.04 | gzip > ccr.ccs.tencentyun.com-cube-studio-notebook-jupyter-ubuntu22.04.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/volcano:20230601 && docker save ccr.ccs.tencentyun.com/cube-studio/volcano:20230601 | gzip > ccr.ccs.tencentyun.com-cube-studio-volcano-20230601.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/llm-server:20240601 && docker save ccr.ccs.tencentyun.com/cube-studio/llm-server:20240601 | gzip > ccr.ccs.tencentyun.com-cube-studio-llm-server-20240601.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu-machinelearning && docker save ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu-machinelearning | gzip > ccr.ccs.tencentyun.com-cube-studio-notebook-jupyter-ubuntu-machinelearning.tar.gz &
docker pull docker:23.0.4 && docker save docker:23.0.4 | gzip > docker-23.0.4.tar.gz &
docker pull argoproj/workflow-controller:v3.4.3 && docker save argoproj/workflow-controller:v3.4.3 | gzip > argoproj-workflow-controller-v3.4.3.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/tf:20230801 && docker save ccr.ccs.tencentyun.com/cube-studio/tf:20230801 | gzip > ccr.ccs.tencentyun.com-cube-studio-tf-20230801.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook:vscode-ubuntu-cpu-base && docker save ccr.ccs.tencentyun.com/cube-studio/notebook:vscode-ubuntu-cpu-base | gzip > ccr.ccs.tencentyun.com-cube-studio-notebook-vscode-ubuntu-cpu-base.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/data-process:20230501 && docker save ccr.ccs.tencentyun.com/cube-studio/data-process:20230501 | gzip > ccr.ccs.tencentyun.com-cube-studio-data-process-20230501.tar.gz &
docker pull volcanosh/vc-scheduler:v1.7.0 && docker save volcanosh/vc-scheduler:v1.7.0 | gzip > volcanosh-vc-scheduler-v1.7.0.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/ml-server:20240601 && docker save ccr.ccs.tencentyun.com/cube-studio/ml-server:20240601 | gzip > ccr.ccs.tencentyun.com-cube-studio-ml-server-20240601.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/video-audio:20210601 && docker save ccr.ccs.tencentyun.com/cube-studio/video-audio:20210601 | gzip > ccr.ccs.tencentyun.com-cube-studio-video-audio-20210601.tar.gz &
docker pull quay.io/prometheus-operator/prometheus-config-reloader:v0.46.0 && docker save quay.io/prometheus-operator/prometheus-config-reloader:v0.46.0 | gzip > quay.io-prometheus-operator-prometheus-config-reloader-v0.46.0.tar.gz &
docker pull bitnami/redis:6.2.12 && docker save bitnami/redis:6.2.12 | gzip > bitnami-redis-6.2.12.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/aihub:stable-diffusion-webui && docker save ccr.ccs.tencentyun.com/cube-studio/aihub:stable-diffusion-webui | gzip > ccr.ccs.tencentyun.com-cube-studio-aihub-stable-diffusion-webui.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/ubuntu-gpu:cuda11.8.0-cudnn8-python3.9 && docker save ccr.ccs.tencentyun.com/cube-studio/ubuntu-gpu:cuda11.8.0-cudnn8-python3.9 | gzip > ccr.ccs.tencentyun.com-cube-studio-ubuntu-gpu-cuda11.8.0-cudnn8-python3.9.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu22.04-cuda11.8.0-cudnn8 && docker save ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu22.04-cuda11.8.0-cudnn8 | gzip > ccr.ccs.tencentyun.com-cube-studio-notebook-jupyter-ubuntu22.04-cuda11.8.0-cudnn8.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/nni:20230601 && docker save ccr.ccs.tencentyun.com/cube-studio/nni:20230601 | gzip > ccr.ccs.tencentyun.com-cube-studio-nni-20230601.tar.gz &
docker pull kubeflow/training-operator:v1-8a066f9 && docker save kubeflow/training-operator:v1-8a066f9 | gzip > kubeflow-training-operator-v1-8a066f9.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu-cpu-1.0.0 && docker save ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu-cpu-1.0.0 | gzip > ccr.ccs.tencentyun.com-cube-studio-notebook-jupyter-ubuntu-cpu-1.0.0.tar.gz &
docker pull bitnami/kube-rbac-proxy:0.14.1 && docker save bitnami/kube-rbac-proxy:0.14.1 | gzip > bitnami-kube-rbac-proxy-0.14.1.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/yolov7:2024.01 && docker save ccr.ccs.tencentyun.com/cube-studio/yolov7:2024.01 | gzip > ccr.ccs.tencentyun.com-cube-studio-yolov7-2024.01.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu-deeplearning && docker save ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu-deeplearning | gzip > ccr.ccs.tencentyun.com-cube-studio-notebook-jupyter-ubuntu-deeplearning.tar.gz &
docker pull istio/proxyv2:1.15.0 && docker save istio/proxyv2:1.15.0 | gzip > istio-proxyv2-1.15.0.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/ubuntu-gpu:cuda11.8.0-cudnn8-python3.9-dev && docker save ccr.ccs.tencentyun.com/cube-studio/ubuntu-gpu:cuda11.8.0-cudnn8-python3.9-dev | gzip > ccr.ccs.tencentyun.com-cube-studio-ubuntu-gpu-cuda11.8.0-cudnn8-python3.9-dev.tar.gz &
docker pull mysql:8.0.32 && docker save mysql:8.0.32 | gzip > mysql-8.0.32.tar.gz &
docker pull kubernetesui/metrics-scraper:v1.0.8 && docker save kubernetesui/metrics-scraper:v1.0.8 | gzip > kubernetesui-metrics-scraper-v1.0.8.tar.gz &
docker pull argoproj/argocli:v3.4.3 && docker save argoproj/argocli:v3.4.3 | gzip > argoproj-argocli-v3.4.3.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/dataset:20240501 && docker save ccr.ccs.tencentyun.com/cube-studio/dataset:20240501 | gzip > ccr.ccs.tencentyun.com-cube-studio-dataset-20240501.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/phpmyadmin && docker save ccr.ccs.tencentyun.com/cube-studio/phpmyadmin | gzip > ccr.ccs.tencentyun.com-cube-studio-phpmyadmin.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/neo4j:4.4 && docker save ccr.ccs.tencentyun.com/cube-studio/neo4j:4.4 | gzip > ccr.ccs.tencentyun.com-cube-studio-neo4j-4.4.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/model_download:20240501 && docker save ccr.ccs.tencentyun.com/cube-studio/model_download:20240501 | gzip > ccr.ccs.tencentyun.com-cube-studio-model_download-20240501.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/llama-factory:20240410 && docker save ccr.ccs.tencentyun.com/cube-studio/llama-factory:20240410 | gzip > ccr.ccs.tencentyun.com-cube-studio-llama-factory-20240410.tar.gz &
docker pull volcanosh/vc-webhook-manager:v1.7.0 && docker save volcanosh/vc-webhook-manager:v1.7.0 | gzip > volcanosh-vc-webhook-manager-v1.7.0.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu-bigdata && docker save ccr.ccs.tencentyun.com/cube-studio/notebook:jupyter-ubuntu-bigdata | gzip > ccr.ccs.tencentyun.com-cube-studio-notebook-jupyter-ubuntu-bigdata.tar.gz &
docker pull busybox:1.36.0 && docker save busybox:1.36.0 | gzip > busybox-1.36.0.tar.gz &
docker pull istio/pilot:1.15.0 && docker save istio/pilot:1.15.0 | gzip > istio-pilot-1.15.0.tar.gz &
docker pull quay.io/prometheus-operator/prometheus-operator:v0.46.0 && docker save quay.io/prometheus-operator/prometheus-operator:v0.46.0 | gzip > quay.io-prometheus-operator-prometheus-operator-v0.46.0.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/datax:20240501 && docker save ccr.ccs.tencentyun.com/cube-studio/datax:20240501 | gzip > ccr.ccs.tencentyun.com-cube-studio-datax-20240501.tar.gz &
docker pull grafana/grafana:9.1.5 && docker save grafana/grafana:9.1.5 | gzip > grafana-grafana-9.1.5.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/ray:gpu-20240101 && docker save ccr.ccs.tencentyun.com/cube-studio/ray:gpu-20240101 | gzip > ccr.ccs.tencentyun.com-cube-studio-ray-gpu-20240101.tar.gz &
docker pull kubernetesui/dashboard:v2.6.1 && docker save kubernetesui/dashboard:v2.6.1 | gzip > kubernetesui-dashboard-v2.6.1.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/ray-sklearn:20240101 && docker save ccr.ccs.tencentyun.com/cube-studio/ray-sklearn:20240101 | gzip > ccr.ccs.tencentyun.com-cube-studio-ray-sklearn-20240101.tar.gz &
docker pull python:3.9 && docker save python:3.9 | gzip > python-3.9.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/python:strong && docker save ccr.ccs.tencentyun.com/cube-studio/python:strong | gzip > ccr.ccs.tencentyun.com-cube-studio-python-strong.tar.gz &
docker pull nvidia/k8s-device-plugin:v0.11.0-ubuntu20.04 && docker save nvidia/k8s-device-plugin:v0.11.0-ubuntu20.04 | gzip > nvidia-k8s-device-plugin-v0.11.0-ubuntu20.04.tar.gz &
docker pull volcanosh/vc-controller-manager:v1.7.0 && docker save volcanosh/vc-controller-manager:v1.7.0 | gzip > volcanosh-vc-controller-manager-v1.7.0.tar.gz &
docker pull minio/minio:RELEASE.2023-04-20T17-56-55Z && docker save minio/minio:RELEASE.2023-04-20T17-56-55Z | gzip > minio-minio-RELEASE.2023-04-20T17-56-55Z.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/model_register:20230501 && docker save ccr.ccs.tencentyun.com/cube-studio/model_register:20230501 | gzip > ccr.ccs.tencentyun.com-cube-studio-model_register-20230501.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/torchserve:0.5.3-cpu && docker save ccr.ccs.tencentyun.com/cube-studio/torchserve:0.5.3-cpu | gzip > ccr.ccs.tencentyun.com-cube-studio-torchserve-0.5.3-cpu.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/patrikx3:latest && docker save ccr.ccs.tencentyun.com/cube-studio/patrikx3:latest | gzip > ccr.ccs.tencentyun.com-cube-studio-patrikx3-latest.tar.gz &
docker pull carlosedp/addon-resizer:v1.8.4 && docker save carlosedp/addon-resizer:v1.8.4 | gzip > carlosedp-addon-resizer-v1.8.4.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/win:11 && docker save ccr.ccs.tencentyun.com/cube-studio/win:11 | gzip > ccr.ccs.tencentyun.com-cube-studio-win-11.tar.gz &
docker pull nvidia/dcgm-exporter:3.1.7-3.1.4-ubuntu20.04 && docker save nvidia/dcgm-exporter:3.1.7-3.1.4-ubuntu20.04 | gzip > nvidia-dcgm-exporter-3.1.7-3.1.4-ubuntu20.04.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/spark-operator:1.3.8-3.1.1 && docker save ccr.ccs.tencentyun.com/cube-studio/spark-operator:1.3.8-3.1.1 | gzip > ccr.ccs.tencentyun.com-cube-studio-spark-operator-1.3.8-3.1.1.tar.gz &
docker pull prom/prometheus:v2.27.1 && docker save prom/prometheus:v2.27.1 | gzip > prom-prometheus-v2.27.1.tar.gz &
docker pull argoproj/argoexec:v3.4.3 && docker save argoproj/argoexec:v3.4.3 | gzip > argoproj-argoexec-v3.4.3.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/prometheus-adapter:v0.9.1 && docker save ccr.ccs.tencentyun.com/cube-studio/prometheus-adapter:v0.9.1 | gzip > ccr.ccs.tencentyun.com-cube-studio-prometheus-adapter-v0.9.1.tar.gz &
docker pull prom/node-exporter:v1.5.0 && docker save prom/node-exporter:v1.5.0 | gzip > prom-node-exporter-v1.5.0.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/notebook:vscode-ubuntu-gpu-base && docker save ccr.ccs.tencentyun.com/cube-studio/notebook:vscode-ubuntu-gpu-base | gzip > ccr.ccs.tencentyun.com-cube-studio-notebook-vscode-ubuntu-gpu-base.tar.gz &
docker pull ubuntu:20.04 && docker save ubuntu:20.04 | gzip > ubuntu-20.04.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/tritonserver:22.07-py3 && docker save ccr.ccs.tencentyun.com/cube-studio/tritonserver:22.07-py3 | gzip > ccr.ccs.tencentyun.com-cube-studio-tritonserver-22.07-py3.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/pytorch:20230801 && docker save ccr.ccs.tencentyun.com/cube-studio/pytorch:20230801 | gzip > ccr.ccs.tencentyun.com-cube-studio-pytorch-20230801.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/tfserving:2.3.4 && docker save ccr.ccs.tencentyun.com/cube-studio/tfserving:2.3.4 | gzip > ccr.ccs.tencentyun.com-cube-studio-tfserving-2.3.4.tar.gz &
docker pull alpine:3.10 && docker save alpine:3.10 | gzip > alpine-3.10.tar.gz &
docker pull ccr.ccs.tencentyun.com/cube-studio/offline-predict:20230801 && docker save ccr.ccs.tencentyun.com/cube-studio/offline-predict:20230801 | gzip > ccr.ccs.tencentyun.com-cube-studio-offline-predict-20230801.tar.gz &

wait
