gunzip -c ccr.ccs.tencentyun.com-cube-studio-deploy-service-20240601.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-notebook-jupyter-ubuntu22.04.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-volcano-20230601.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-llm-server-20240601.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-notebook-jupyter-ubuntu-machinelearning.tar.gz | docker load &
gunzip -c docker-23.0.4.tar.gz | docker load &
gunzip -c argoproj-workflow-controller-v3.4.3.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-tf-20230801.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-notebook-vscode-ubuntu-cpu-base.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-data-process-20230501.tar.gz | docker load &
gunzip -c volcanosh-vc-scheduler-v1.7.0.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-ml-server-20240601.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-video-audio-20210601.tar.gz | docker load &
gunzip -c quay.io-prometheus-operator-prometheus-config-reloader-v0.46.0.tar.gz | docker load &
gunzip -c bitnami-redis-6.2.12.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-aihub-stable-diffusion-webui.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-ubuntu-gpu-cuda11.8.0-cudnn8-python3.9.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-notebook-jupyter-ubuntu22.04-cuda11.8.0-cudnn8.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-nni-20230601.tar.gz | docker load &
gunzip -c kubeflow-training-operator-v1-8a066f9.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-notebook-jupyter-ubuntu-cpu-1.0.0.tar.gz | docker load &
gunzip -c bitnami-kube-rbac-proxy-0.14.1.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-yolov7-2024.01.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-notebook-jupyter-ubuntu-deeplearning.tar.gz | docker load &
gunzip -c istio-proxyv2-1.15.0.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-ubuntu-gpu-cuda11.8.0-cudnn8-python3.9-dev.tar.gz | docker load &
gunzip -c mysql-8.0.32.tar.gz | docker load &
gunzip -c kubernetesui-metrics-scraper-v1.0.8.tar.gz | docker load &
gunzip -c argoproj-argocli-v3.4.3.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-dataset-20240501.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-phpmyadmin.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-neo4j-4.4.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-model_download-20240501.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-llama-factory-20240410.tar.gz | docker load &
gunzip -c volcanosh-vc-webhook-manager-v1.7.0.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-notebook-jupyter-ubuntu-bigdata.tar.gz | docker load &
gunzip -c busybox-1.36.0.tar.gz | docker load &
gunzip -c istio-pilot-1.15.0.tar.gz | docker load &
gunzip -c quay.io-prometheus-operator-prometheus-operator-v0.46.0.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-datax-20240501.tar.gz | docker load &
gunzip -c grafana-grafana-9.1.5.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-ray-gpu-20240101.tar.gz | docker load &
gunzip -c kubernetesui-dashboard-v2.6.1.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-ray-sklearn-20240101.tar.gz | docker load &
gunzip -c python-3.9.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-python-strong.tar.gz | docker load &
gunzip -c nvidia-k8s-device-plugin-v0.11.0-ubuntu20.04.tar.gz | docker load &
gunzip -c volcanosh-vc-controller-manager-v1.7.0.tar.gz | docker load &
gunzip -c minio-minio-RELEASE.2023-04-20T17-56-55Z.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-model_register-20230501.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-torchserve-0.5.3-cpu.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-patrikx3-latest.tar.gz | docker load &
gunzip -c carlosedp-addon-resizer-v1.8.4.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-win-11.tar.gz | docker load &
gunzip -c nvidia-dcgm-exporter-3.1.7-3.1.4-ubuntu20.04.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-spark-operator-1.3.8-3.1.1.tar.gz | docker load &
gunzip -c prom-prometheus-v2.27.1.tar.gz | docker load &
gunzip -c argoproj-argoexec-v3.4.3.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-prometheus-adapter-v0.9.1.tar.gz | docker load &
gunzip -c prom-node-exporter-v1.5.0.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-notebook-vscode-ubuntu-gpu-base.tar.gz | docker load &
gunzip -c ubuntu-20.04.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-tritonserver-22.07-py3.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-pytorch-20230801.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-tfserving-2.3.4.tar.gz | docker load &
gunzip -c alpine-3.10.tar.gz | docker load &
gunzip -c ccr.ccs.tencentyun.com-cube-studio-offline-predict-20230801.tar.gz | docker load &

wait
